#!/bin/bash
#    praiseTex - simple set of programs for creating praise music material, 
#    such as guitar chord sheets and presentation slides
#
#    Copyright (C) 2012 Jeffrey M Brown
#    brown.jeffreym@gmail.com
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

######################################################################
# script for creating presentation slides from the song files passed
# as command-line arguments
#
# example:
#
# ./slides song1.tex song2.tex
#####################################################################

# print error if no arguments are passed
if [ ${#} -eq 0 ]
then
    printf "${0}: you must pass at least one argument\n"
    exit 1
fi

# location of
#songdir=songs

# latex commands for beginning and ending a document
begindoc="\\\begin{document}\n"
enddoc="\\\end{document}\n"

# create string of latex"s \input{} command from files
for file in ${*}
do
    inputfiles+="\\input{${file}}\n"
done

sed '/\\begin{document}/,/\\end{document}/ d' <'latex/slides.tex' >'stmp'

printf "${begindoc}\n" >> stmp
printf "${inputfiles}\n" >> stmp
printf "${enddoc}\n" >> stmp

pdflatex stmp
mv stmp.pdf slides.pdf

# cleaning up temporary files
rm stmp*
